import streamlit as st
from rdkit import Chem
from rdkit.Chem import Draw
from rdkit.Chem import PILImgStructCreator

# ==========================================
# BAB V: DATABASE MAPPING (Nama ke SMILES)
# ==========================================
# SMILES adalah format teks yang dipahami komputer untuk struktur kimia
DATABASE_SMILES = {
    "METANA": "C",
    "ETANA": "CC",
    "ETANOL": "CCO",
    "ASAM ASETAT": "CC(=O)O",
    "BENZENA": "c1ccccc1",
    "ASETON": "CC(=O)C",
    "GLUKOSA": "C(C1C(C(C(C(O1)O)O)O)O)O",
    "ASPIRIN": "CC(=O)Oc1ccccc1C(=O)O",
    "PARACETAMOL": "CC(=O)Nc1ccc(cc1)O",
    "KAFEIN": "CN1C=NC2=C1C(=O)N(C(=O)N2C)C"
}

# ==========================================
# BAB VI: FUNGSI VISUALISASI
# ==========================================
def generate_structure(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol:
        # Menghasilkan gambar molekul
        img = Draw.MolToImage(mol, size=(400, 400))
        return img
    return None

# ==========================================
# INTERFACE STREAMLIT
# ==========================================
st.set_page_config(page_title="ChemDraw Digital AKA", layout="centered")
st.title("🧬 Visualisator Struktur Organik")
st.write("Masukkan nama IUPAC/Trivial untuk memunculkan struktur 2D.")

# Bab II: Input
nama_input = st.text_input("Nama Senyawa (Contoh: Etanol, Benzena, Aspirin):").upper().strip()

# Bab III: Kondisional
if nama_input:
    if nama_input in DATABASE_SMILES:
        smiles_code = DATABASE_SMILES[nama_input]
        
        st.subheader(f"Struktur dari {nama_input}")
        
        # Memanggil Fungsi Bab VI
        gambar = generate_structure(smiles_code)
        
        if gambar:
            st.image(gambar, caption=f"Struktur 2D {nama_input} (Generated by RDKit)")
            
            # Integrasi Bab I: Informasi Data
            st.info(f"SMILES Code (Data Komputer): `{smiles_code}`")
        else:
            st.error("Gagal memproses struktur.")
    else:
        st.warning("Senyawa belum ada di database. Silakan masukkan kode SMILES secara manual:")
        manual_smiles = st.text_input("Masukkan SMILES (Contoh: C1CCCCC1):")
        if manual_smiles:
            gambar_manual = generate_structure(manual_smiles)
            if gambar_manual:
                st.image(gambar_manual)

# ==========================================
# BAB IV: DAFTAR DATABASE
# ==========================================
with st.sidebar:
    st.header("Katalog Senyawa")
    st.write("Senyawa terdaftar di sistem:")
    # Perulangan Bab IV
    for nama in DATABASE_SMILES.keys():
        st.markdown(f"- {nama}")
